import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="h-screen w-screen flex flex-col bg-white">{children}</body>
    </html>
  )
}
